### ISSUE TITLE
Login and folder listing works OK, Download fails

### ISSUE THREAD

**Issue by ou-li** [martinhoefling/dkb-scraping#11]
Very useful tool 👍️ now that DKB are phasing out their archive without providing a user-friendly download option. 

This is as far as I got it to work:

> Downloading folder XXXXXXXXXXXXXX
> 
> Downloading XXXXXXXXXXXXXX links on page 1
> 
> 30 newstyle links to download
> 
> (node:241510) UnhandledPromiseRejectionWarning: TypeError: link.label.replaceAll is not a function
>       at downloadLink (file:///home/YYYYYYYYYY/dkb-scraping/download.js:94:40)
>       at downloadFolderPageLinks (file:///home/YYYYYYYYYY/dkb-scraping/download.js:60:11)
>       at processTicksAndRejections (internal/process/task_queues.js:97:5)
>       at async downloadFolder (file:///home/YYYYYYYYYY/dkb-scraping/download.js:45:5)
>       at async download (file:///YYYYYYYYYY/dkb-scraping/download.js:15:5)
>       at async file:///home/YYYYYYYYYY/dkb-scraping/scrape-dkb.js:12:3
>     
> (node:241510) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> 
> (node:241510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ou-li** [comment]
The first folder name   features dots and spaces.
Could that be an issue?

**Comment by ou-li** [comment]
Looks like the same issue as @comfreak89
https://github.com/martinhoefling/dkb-scraping/issues/6

I will update node.js and report back.

**Comment by ou-li** [comment]
It  works using the recent version of node.js
